### Join employee
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "employeeName": "John Doe"
}

### List employees
GET http://localhost:8080/api/employees

### Announce course
POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "code": "JAVAX-DDD4",
  "title": "Data Driven Design",
  "limit": 1
}

### List courses
GET http://localhost:8080/api/courses

### Enroll
POST http://localhost:8080/api/courses/JAVAX-DDD/enrollments
Content-Type: application/json

{
  "employeeId": 11,
  "courseCode": "JAVAX-DDD"
}

### Leave
DELETE http://localhost:8080/api/employees/1

### Enrollments
GET http://localhost:8080/api/courses/JAVAX-DDD/enrollments
